name: pokedex
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  provider: ^6.0.3
  get_it: ^8.0.2
  event_bus: ^2.0.0
  dio: ^5.7.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  fonts:
        - family: Pokemon
          fonts:
            - asset: fonts/Pokemon-Solid.ttf
            - asset: fonts/Pokemon-Hollow.ttf
              style: italic

  assets:
        - assets/images/
 
  uses-material-design: true

  
  
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 

    
   
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
